version: "3"
services:
  #This file is an example for local testing
  cci-shell:
    image: cci
    entrypoint: /bin/bash
    volumes:
      - ~/gh/concourse-sfdx-resource:/root/test
      - ~/gh/cci-cha:/root/cha
      - ~/.cumulusci/cci-cha:/root/org_dir
    environment:
      CUMULUSCI_KEY: <key>
